version: '3.6'

services:
  db:
    container_name: postgres-container
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  web:
    container_name: django-container
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=misiu
    depends_on:
      - db

volumes:
  postgres_data: