# Generated by Django 2.0.7 on 2018-10-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='opis')),
                ('meeting_description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='kiedy spotkania')),
            ],
        ),
        migrations.CreateModel(
            name='Actual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tytuł')),
                ('content', models.CharField(max_length=25000, verbose_name='zawartość')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='data publikacji')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Nowy artykuł aktualności',
                'ordering': ('-date',),
                'verbose_name_plural': 'Aktualność',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=15000, null=True, verbose_name='treść')),
            ],
            options={
                'verbose_name': 'Ogłoszenie',
                'verbose_name_plural': 'Ogłoszenia',
            },
        ),
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('day', models.CharField(choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=20)),
                ('church', models.CharField(max_length=30, verbose_name=(('f', 'św. Faustyny'), ('mb', 'Miłosierdzia Bożego')))),
                ('display_start', models.DateField()),
                ('display_end', models.DateField()),
                ('display_now', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='opis')),
            ],
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tytuł')),
                ('description', models.CharField(max_length=25000, verbose_name='opis')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='data publikacji')),
                ('date_event', models.DateField(blank=True, null=True, verbose_name='data wydarzenia')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Actual')),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(verbose_name='godzina mszy')),
                ('church', models.CharField(choices=[('f', 'św. Faustyny'), ('mb', 'Miłosierdzia Bożego')], max_length=50, verbose_name='kościół')),
            ],
            options={
                'verbose_name': 'Msza święta',
                'verbose_name_plural': 'Msze',
            },
        ),
        migrations.CreateModel(
            name='ImageWithCaption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
                ('galery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Galery')),
            ],
        ),
        migrations.CreateModel(
            name='Intentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('hour', models.TimeField(verbose_name='godzina')),
                ('title', models.CharField(max_length=200, verbose_name='nazwa intencji')),
            ],
            options={
                'verbose_name': 'Intencja',
                'verbose_name_plural': 'Intencje',
            },
        ),
        migrations.CreateModel(
            name='IntentionWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('display_now', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MassSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='nazwa sezonu')),
                ('season_start', models.DateField(blank=True, null=True, verbose_name='Pierwszy dzień sezonu')),
                ('season_end', models.DateField(blank=True, null=True, verbose_name='Ostatni dzień sezonu')),
                ('sunday', models.BooleanField(default=False, verbose_name='Niedziela')),
            ],
            options={
                'verbose_name': 'Lista mszy w sezonie',
                'verbose_name_plural': 'Schemat mszy',
            },
        ),
        migrations.CreateModel(
            name='MassSchemaRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sunday', models.BooleanField()),
                ('church', models.CharField(max_length=30, verbose_name=(('f', 'św. Faustyny'), ('mb', 'Miłosierdzia Bożego')))),
                ('hours', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=15, verbose_name='dzien tygodnia')),
                ('start', models.TimeField(verbose_name='od godziny')),
                ('end', models.TimeField(verbose_name='do godziny')),
            ],
            options={
                'verbose_name': 'Godziny działania kancelarii w danym dniu',
                'verbose_name_plural': 'Godziny działania kancelarii',
            },
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='imię i nazwisko')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sacrament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nazwa sakramentu')),
                ('content', models.CharField(max_length=15000, verbose_name='opis')),
            ],
            options={
                'verbose_name': 'Sakrament',
                'verbose_name_plural': 'Sakramenty',
            },
        ),
        migrations.CreateModel(
            name='SectionRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_kind', models.CharField(max_length=50)),
                ('row_content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SubPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tytuł')),
                ('shortcut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Co wyświetlać w karcie')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupa podstron(0-jeśli nowa)')),
            ],
            options={
                'verbose_name': 'Podstrona',
                'verbose_name_plural': 'Podstrony',
            },
        ),
        migrations.CreateModel(
            name='WeekAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='niedziela')),
            ],
            options={
                'verbose_name': 'Ogłoszenia duszpasterskie',
                'ordering': ('-date',),
                'verbose_name_plural': 'Ogłoszenia duszpasterskie',
            },
        ),
        migrations.CreateModel(
            name='WeekOfMass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(blank=True, choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=12, null=True, verbose_name='Dzień tygodnia')),
                ('mass_chema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MassSchema', verbose_name='Lista mszy w sezonie')),
            ],
        ),
        migrations.AddField(
            model_name='intentions',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.IntentionWeek'),
        ),
        migrations.AddField(
            model_name='hour',
            name='mass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MassSchema', verbose_name='msza'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='week_announcment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WeekAnnouncement', verbose_name='Ogłoszenia'),
        ),
    ]
