# Generated by Django 2.0.7 on 2018-10-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekofmass',
            old_name='mass_chema',
            new_name='mass_schema',
        ),
        migrations.AddField(
            model_name='ceremony',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ceremony',
            name='day',
            field=models.CharField(blank=True, choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ceremony',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
