# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180204_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mass',
            name='hours',
        ),
        migrations.AddField(
            model_name='hour',
            name='mass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Mass'),
        ),
        migrations.AlterField(
            model_name='hour',
            name='hour',
            field=models.TimeField(blank=True, null=True, verbose_name='godzina mszy'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='church',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mass',
            name='season_end',
            field=models.DateField(blank=True, null=True, verbose_name='Ostatni dzień sezonu'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='season_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='nazwa sezonu'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='season_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
