# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180204_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='tytuł')),
                ('content', models.CharField(max_length=1000, verbose_name='zawartość')),
                ('date', models.DateTimeField(verbose_name='data publikacji')),
            ],
            options={
                'verbose_name': 'Nowy artykuł aktualności',
                'verbose_name_plural': 'Aktualność',
            },
        ),
        migrations.CreateModel(
            name='Announcment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treść', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Ogłoszenie',
                'verbose_name_plural': 'Ogłoszenia',
            },
        ),
        migrations.CreateModel(
            name='Intentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='termin_mszy')),
                ('title', models.CharField(max_length=100, verbose_name='nazwa intencji')),
            ],
            options={
                'verbose_name': 'Intencja',
                'verbose_name_plural': 'Intencje',
            },
        ),
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, verbose_name='dzien tygodnia')),
                ('start', models.IntegerField(verbose_name='od godziny')),
                ('end', models.IntegerField(verbose_name='do godziny')),
            ],
            options={
                'verbose_name': 'Godziny działania kancelarii w danym dniu',
                'verbose_name_plural': 'Godziny działania kancelarii',
            },
        ),
        migrations.CreateModel(
            name='SubPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tytuł')),
                ('shortcut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Co wyświetlać w karcie')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupa podstron(0-jeśli nowa)')),
            ],
            options={
                'verbose_name': 'Podstrona',
                'verbose_name_plural': 'Podstrony',
            },
        ),
        migrations.CreateModel(
            name='WeekAnnouncment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='niedziela')),
            ],
            options={
                'verbose_name': 'Ogłoszenia duszpasterskie',
                'verbose_name_plural': 'Ogłoszenia duszpasterskie',
            },
        ),
        migrations.AlterModelOptions(
            name='hour',
            options={'verbose_name': 'godzina', 'verbose_name_plural': 'godziny mszy'},
        ),
        migrations.AlterModelOptions(
            name='mass',
            options={'verbose_name': 'Msza święta', 'verbose_name_plural': 'Msze święte'},
        ),
        migrations.AlterField(
            model_name='hour',
            name='mass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Mass', verbose_name='msza'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='season_start',
            field=models.DateField(blank=True, null=True, verbose_name='Pierwszy dzień sezonu'),
        ),
        migrations.AddField(
            model_name='announcment',
            name='ogloszenia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WeekAnnouncment', verbose_name='Ogłoszenia'),
        ),
    ]
