# Generated by Django 2.0.7 on 2018-10-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181012_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremony',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officehours',
            name='day',
            field=models.CharField(choices=[('Brak', 'Brak'), ('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=15, verbose_name='dzien tygodnia'),
        ),
        migrations.AlterField(
            model_name='weekofmass',
            name='week_day',
            field=models.CharField(blank=True, choices=[('Brak', 'Brak'), ('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=12, null=True, verbose_name='Dzień tygodnia'),
        ),
    ]
