# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180204_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='mass',
            name='week_day',
            field=models.CharField(blank=True, choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek'), (6, 'Sobota'), (7, 'Niedziela')], max_length=12, null=True),
        ),
    ]
