# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mass_week_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mass',
            options={'verbose_name': 'Msze święte w dniu', 'verbose_name_plural': 'Msze święte'},
        ),
        migrations.RenameField(
            model_name='announcment',
            old_name='ogloszenia',
            new_name='week_announcment',
        ),
        migrations.RemoveField(
            model_name='announcment',
            name='treść',
        ),
        migrations.AddField(
            model_name='announcment',
            name='content',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='church',
            field=models.CharField(blank=True, choices=[(0, 'św. Faustyny'), (1, 'Miłosierdzia Bożego')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mass',
            name='week_day',
            field=models.CharField(blank=True, choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek'), (6, 'Sobota'), (7, 'Niedziela')], max_length=12, null=True, verbose_name='Dzień tygodnia'),
        ),
    ]
