# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 20:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180207_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentions',
            name='week',
            field=models.CharField(choices=[('I Tydzień', 'I Tydzień'), ('II Tydzień', 'II Tydzień')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actual',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 21, 6, 39, 432569), verbose_name='data publikacji'),
        ),
        migrations.AlterField(
            model_name='intentions',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hour'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='church',
            field=models.CharField(blank=True, choices=[('św. Faustyny', 'św. Faustyny'), ('Miłosierdzia Bożego', 'Miłosierdzia Bożego')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mass',
            name='week_day',
            field=models.CharField(blank=True, choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=12, null=True, verbose_name='Dzień tygodnia'),
        ),
        migrations.AlterField(
            model_name='officehours',
            name='day',
            field=models.CharField(choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=10, verbose_name='dzien tygodnia'),
        ),
    ]
