# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 20:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180306_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actual',
            options={'ordering': ('-date',), 'verbose_name': 'Nowy artykuł aktualności', 'verbose_name_plural': 'Aktualność'},
        ),
        migrations.AlterField(
            model_name='actual',
            name='content',
            field=models.CharField(max_length=25000, verbose_name='zawartość'),
        ),
        migrations.AlterField(
            model_name='actual',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 10, 21, 12, 10, 238165), verbose_name='data publikacji'),
        ),
    ]
