# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 18:35
from __future__ import unicode_literals

import app.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180313_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='massschema',
            name='week_of_mass',
            field=app.models.ListField(choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], default='', verbose_name='Dni których dotyczy rozpiska'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actual',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 13, 19, 34, 56, 614970), verbose_name='data publikacji'),
        ),
        migrations.AlterField(
            model_name='hour',
            name='church',
            field=models.CharField(blank=True, choices=[('św. Faustyny', 'św. Faustyny'), ('Miłosierdzia Bożego', 'Miłosierdzia Bożego')], max_length=50, null=True, verbose_name='kościół'),
        ),
        migrations.AlterField(
            model_name='hour',
            name='mass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.MassSchema', verbose_name='msza'),
        ),
    ]
