# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180313_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 15, 17, 17, 10, 486018), verbose_name='data publikacji'),
        ),
    ]
