# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 16:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180315_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massschema',
            name='week_of_mass',
        ),
        migrations.AddField(
            model_name='massschema',
            name='friday',
            field=models.BooleanField(default=False, verbose_name='Piątek'),
        ),
        migrations.AddField(
            model_name='massschema',
            name='monday',
            field=models.BooleanField(default=False, verbose_name='Poniedziałek'),
        ),
        migrations.AddField(
            model_name='massschema',
            name='saturday',
            field=models.BooleanField(default=False, verbose_name='Niedziela'),
        ),
        migrations.AddField(
            model_name='massschema',
            name='sunday',
            field=models.BooleanField(default=False, verbose_name='Sobota'),
        ),
        migrations.AddField(
            model_name='massschema',
            name='thursday',
            field=models.BooleanField(default=False, verbose_name='Czwartek'),
        ),
        migrations.AddField(
            model_name='massschema',
            name='tuesday',
            field=models.BooleanField(default=False, verbose_name='Wtorek'),
        ),
        migrations.AddField(
            model_name='massschema',
            name='wednesday',
            field=models.BooleanField(default=False, verbose_name='Środa'),
        ),
        migrations.AlterField(
            model_name='actual',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 15, 17, 46, 52, 968692), verbose_name='data publikacji'),
        ),
    ]
