# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180315_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1500, null=True, verbose_name='treść')),
            ],
            options={
                'verbose_name_plural': 'Ogłoszenia',
                'verbose_name': 'Ogłoszenie',
            },
        ),
        migrations.CreateModel(
            name='IntentionWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='announcment',
            name='week_announcment',
        ),
        migrations.AlterModelOptions(
            name='hour',
            options={'verbose_name': 'Msza święta', 'verbose_name_plural': 'Msze'},
        ),
        migrations.AlterModelOptions(
            name='weekannouncment',
            options={'ordering': ('-date',), 'verbose_name': 'Ogłoszenia duszpasterskie', 'verbose_name_plural': 'Ogłoszenia duszpasterskie'},
        ),
        migrations.AddField(
            model_name='intentions',
            name='hour',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='godzina'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actual',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 13, 51, 51, 300441), verbose_name='data publikacji'),
        ),
        migrations.AlterField(
            model_name='intentions',
            name='date',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='intentions',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.IntentionWeek'),
        ),
        migrations.DeleteModel(
            name='Announcment',
        ),
        migrations.AddField(
            model_name='announcement',
            name='week_announcment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WeekAnnouncment', verbose_name='Ogłoszenia'),
        ),
    ]
