# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 14:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180317_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 15, 53, 10, 797613), verbose_name='data publikacji'),
        ),
    ]
