# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180317_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sacrament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nazwa sakramentu')),
                ('content', models.CharField(max_length=15000, verbose_name='opis')),
            ],
            options={
                'verbose_name': 'Sakrament',
                'verbose_name_plural': 'Sakramenty',
            },
        ),
        migrations.AlterField(
            model_name='actual',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 20, 12, 53, 151308), verbose_name='data publikacji'),
        ),
        migrations.AlterField(
            model_name='actual',
            name='title',
            field=models.CharField(max_length=200, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='intentions',
            name='title',
            field=models.CharField(max_length=200, verbose_name='nazwa intencji'),
        ),
        migrations.AlterField(
            model_name='massschema',
            name='season_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nazwa sezonu'),
        ),
        migrations.AlterField(
            model_name='officehours',
            name='day',
            field=models.CharField(choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=15, verbose_name='dzien tygodnia'),
        ),
    ]
