# Generated by Django 2.0.7 on 2018-07-11 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180707_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('day', models.CharField(choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=20)),
                ('church', models.CharField(max_length=30, verbose_name=(('św. Faustyny', 'św. Faustyny'), ('Miłosierdzia Bożego', 'Miłosierdzia Bożego')))),
                ('display_start', models.DateField()),
                ('display_end', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='actual',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 17, 3, 14, 814190), verbose_name='data publikacji'),
        ),
    ]
