# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180711_1703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeekAnnouncment',
            new_name='WeekAnnouncement',
        ),
        migrations.AlterField(
            model_name='actual',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 16, 59, 46, 605509), verbose_name='data publikacji'),
        ),
        migrations.AlterField(
            model_name='ceremony',
            name='church',
            field=models.CharField(max_length=30, verbose_name=(('f', 'św. Faustyny'), ('mb', 'Miłosierdzia Bożego'))),
        ),
        migrations.AlterField(
            model_name='ceremony',
            name='day',
            field=models.CharField(choices=[('pon', 'Poniedziałek'), ('wt', 'Wtorek'), ('sr', 'Środa'), ('cz', 'Czwartek'), ('pt', 'Piątek'), ('sb', 'Sobota'), ('nd', 'Niedziela')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hour',
            name='church',
            field=models.CharField(blank=True, choices=[('f', 'św. Faustyny'), ('mb', 'Miłosierdzia Bożego')], max_length=50, null=True, verbose_name='kościół'),
        ),
        migrations.AlterField(
            model_name='officehours',
            name='day',
            field=models.CharField(choices=[('pon', 'Poniedziałek'), ('wt', 'Wtorek'), ('sr', 'Środa'), ('cz', 'Czwartek'), ('pt', 'Piątek'), ('sb', 'Sobota'), ('nd', 'Niedziela')], max_length=15, verbose_name='dzien tygodnia'),
        ),
        migrations.AlterField(
            model_name='weekofmass',
            name='week_day',
            field=models.CharField(blank=True, choices=[('pon', 'Poniedziałek'), ('wt', 'Wtorek'), ('sr', 'Środa'), ('cz', 'Czwartek'), ('pt', 'Piątek'), ('sb', 'Sobota'), ('nd', 'Niedziela')], max_length=12, null=True, verbose_name='Dzień tygodnia'),
        ),
    ]
