# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 07:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180804_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremony',
            name='display_now',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actual',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 9, 0, 49, 901787), verbose_name='data publikacji'),
        ),
        migrations.AlterField(
            model_name='hour',
            name='church',
            field=models.CharField(choices=[('f', 'św. Faustyny'), ('mb', 'Miłosierdzia Bożego')], default='mb', max_length=50, verbose_name='kościół'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hour',
            name='hour',
            field=models.TimeField(default='7:00', verbose_name='godzina mszy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hour',
            name='mass',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.MassSchema', verbose_name='msza'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intentionweek',
            name='week',
            field=models.DateField(max_length=200),
        ),
    ]
