# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180809_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 9, 6, 40, 34919), verbose_name='data publikacji'),
        ),
        migrations.AlterField(
            model_name='ceremony',
            name='day',
            field=models.CharField(choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ceremony',
            name='display_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='officehours',
            name='day',
            field=models.CharField(choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=15, verbose_name='dzien tygodnia'),
        ),
        migrations.AlterField(
            model_name='weekofmass',
            name='week_day',
            field=models.CharField(blank=True, choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=12, null=True, verbose_name='Dzień tygodnia'),
        ),
    ]
