# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 07:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20180809_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentionweek',
            name='display_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actual',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 9, 30, 52, 68916), verbose_name='data publikacji'),
        ),
    ]
