# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20180809_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='opis')),
                ('meeting_description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='kiedy spotkania')),
            ],
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='opis')),
            ],
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tytuł')),
                ('description', models.CharField(max_length=25000, verbose_name='opis')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='data publikacji')),
            ],
        ),
        migrations.CreateModel(
            name='ImageWithCaption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
                ('galery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Galery')),
            ],
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='imię i nazwisko')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='weekannouncement',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actual',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='data publikacji'),
        ),
        migrations.AddField(
            model_name='galery',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Actual'),
        ),
    ]
