# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20180817_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='date_event',
            field=models.DateField(blank=True, null=True, verbose_name='data wydarzenia'),
        ),
    ]
