# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 14:25
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20180819_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewithcaption',
            name='image_all',
            field=stdimage.models.StdImageField(blank=True, upload_to='path/to/img'),
        ),
    ]
